apiVersion: v1
kind: Service
metadata:
  name: document-service-svc
  namespace: proptuity-dev
spec:
  selector:
    app: document-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081
  type: ClusterIP