# Create this secret manually with your GCS credentials
# kubectl create secret generic gcs-credentials --from-file=gcs-storage.json=src/main/resources/gcs-storage.json -n proptuity-dev

apiVersion: v1
kind: Secret
metadata:
  name: gcs-credentials
  namespace: proptuity-dev
type: Opaque
# data:
#   gcs-storage.json: <base64-encoded-content>