apiVersion: v1
kind: Pod
metadata:
  name: mongo-connectivity-test
spec:
  containers:
    - name: mongo-connectivity-test
      image: ubuntu:20.04
      command: ["/bin/bash", "-c", "apt-get update && apt-get install -y curl gnupg wget && \
                wget -qO- https://www.mongodb.org/static/pgp/server-8.0.asc | tee /etc/apt/trusted.gpg.d/server-8.0.asc && \
                echo 'deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/8.0 multiverse' | tee /etc/apt/sources.list.d/mongodb-org-8.0.list && \
                apt-get update && apt-get install -y mongodb-mongosh && sleep 3600"]
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
