apiVersion: v1
kind: Service
metadata:
  name: user-auth-api-service
  namespace: proptuity-dev
spec:
  selector:
    app: user-auth-api
  ports:
    - protocol: TCP
      port: 80  # Exposing port 80 externally or for internal access
      targetPort: 3000  # The port the application is actually listening on
  type: ClusterIP  # Internal access within the cluster