apiVersion: v1
kind: Service
metadata:
  name: user-auth-api-service
  namespace: proptuity-dev
  annotations: 
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "http-hc-config"}'
spec:
  selector:
    app: user-auth-api
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 30218

---

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: http-hc-config
  namespace: proptuity-dev
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 3000
    type: HTTP
    requestPath: /user-auth/apphealth
